export interface BlogPostMeta {
  slug: string;
  titleKey: string;
  descKey: string;
  contentKey: string;
  date: string;
  readTime: number;
  tags: string[];
  category: string;
}

export const blogPosts: BlogPostMeta[] = [
  {
    slug: 'ultimate-guide-to-merging-pdf-files',
    titleKey: 'blog.posts.mergeGuide.title',
    descKey: 'blog.posts.mergeGuide.desc',
    contentKey: 'blog.posts.mergeGuide.content',
    date: '2026-08-06',
    readTime: 8,
    tags: ['merge', 'pdf', 'guide', 'productivity'],
    category: 'Guides',
  },
  {
    slug: 'pdf-security-protecting-your-documents',
    titleKey: 'blog.posts.pdfSecurity.title',
    descKey: 'blog.posts.pdfSecurity.desc',
    contentKey: 'blog.posts.pdfSecurity.content',
    date: '2026-08-05',
    readTime: 10,
    tags: ['security', 'privacy', 'password', 'encryption'],
    category: 'Security',
  },
  {
    slug: 'how-to-reduce-pdf-file-size',
    titleKey: 'blog.posts.compressGuide.title',
    descKey: 'blog.posts.compressGuide.desc',
    contentKey: 'blog.posts.compressGuide.content',
    date: '2026-08-04',
    readTime: 7,
    tags: ['compress', 'file-size', 'optimization'],
    category: 'Guides',
  },
  {
    slug: 'pdf-to-word-conversion-complete-guide',
    titleKey: 'blog.posts.pdfToWord.title',
    descKey: 'blog.posts.pdfToWord.desc',
    contentKey: 'blog.posts.pdfToWord.content',
    date: '2026-08-03',
    readTime: 9,
    tags: ['conversion', 'word', 'docx', 'text-extraction'],
    category: 'Conversion',
  },
  {
    slug: 'history-of-pdf-format',
    titleKey: 'blog.posts.pdfHistory.title',
    descKey: 'blog.posts.pdfHistory.desc',
    contentKey: 'blog.posts.pdfHistory.content',
    date: '2026-08-02',
    readTime: 12,
    tags: ['history', 'pdf', 'adobe', 'document-format'],
    category: 'Knowledge',
  },
  {
    slug: 'pdf-vs-docx-which-format-to-use',
    titleKey: 'blog.posts.pdfVsDocx.title',
    descKey: 'blog.posts.pdfVsDocx.desc',
    contentKey: 'blog.posts.pdfVsDocx.content',
    date: '2026-08-01',
    readTime: 8,
    tags: ['pdf', 'docx', 'comparison', 'formats'],
    category: 'Comparison',
  },
  {
    slug: 'what-is-ocr-and-how-does-it-work',
    titleKey: 'blog.posts.ocrGuide.title',
    descKey: 'blog.posts.ocrGuide.desc',
    contentKey: 'blog.posts.ocrGuide.content',
    date: '2026-07-31',
    readTime: 11,
    tags: ['ocr', 'scanning', 'text-recognition', 'technology'],
    category: 'Technology',
  },
  {
    slug: 'how-to-fill-pdf-forms-online',
    titleKey: 'blog.posts.pdfForms.title',
    descKey: 'blog.posts.pdfForms.desc',
    contentKey: 'blog.posts.pdfForms.content',
    date: '2026-07-30',
    readTime: 7,
    tags: ['forms', 'fill', 'interactive', 'guide'],
    category: 'Guides',
  },
  {
    slug: 'free-pdf-editing-tools-comparison',
    titleKey: 'blog.posts.freeEditing.title',
    descKey: 'blog.posts.freeEditing.desc',
    contentKey: 'blog.posts.freeEditing.content',
    date: '2026-07-29',
    readTime: 10,
    tags: ['editing', 'free-tools', 'comparison', 'review'],
    category: 'Comparison',
  },
  {
    slug: 'pdf-a-standards-explained',
    titleKey: 'blog.posts.pdfStandards.title',
    descKey: 'blog.posts.pdfStandards.desc',
    contentKey: 'blog.posts.pdfStandards.content',
    date: '2026-07-28',
    readTime: 9,
    tags: ['standards', 'pdf/a', 'archiving', 'compliance'],
    category: 'Knowledge',
  },
  {
    slug: 'pdf-accessibility-making-documents-for-everyone',
    titleKey: 'blog.posts.pdfAccessibility.title',
    descKey: 'blog.posts.pdfAccessibility.desc',
    contentKey: 'blog.posts.pdfAccessibility.content',
    date: '2026-07-27',
    readTime: 10,
    tags: ['accessibility', 'a11y', 'inclusive', 'screen-reader'],
    category: 'Guides',
  },
  {
    slug: 'best-pdf-tools-for-small-business',
    titleKey: 'blog.posts.smallBusiness.title',
    descKey: 'blog.posts.smallBusiness.desc',
    contentKey: 'blog.posts.smallBusiness.content',
    date: '2026-07-26',
    readTime: 8,
    tags: ['business', 'productivity', 'tools', 'small-business'],
    category: 'Business',
  },
  {
    slug: 'how-to-add-watermark-to-pdf',
    titleKey: 'blog.posts.watermarkGuide.title',
    descKey: 'blog.posts.watermarkGuide.desc',
    contentKey: 'blog.posts.watermarkGuide.content',
    date: '2026-07-25',
    readTime: 7,
    tags: ['watermark', 'branding', 'protection', 'guide'],
    category: 'Guides',
  },
  {
    slug: 'how-to-convert-scanned-pdf-to-editable-text',
    titleKey: 'blog.posts.scannedPdf.title',
    descKey: 'blog.posts.scannedPdf.desc',
    contentKey: 'blog.posts.scannedPdf.content',
    date: '2026-07-24',
    readTime: 9,
    tags: ['scanning', 'ocr', 'conversion', 'editable'],
    category: 'Conversion',
  },
  {
    slug: 'pdf-compression-myths-debunked',
    titleKey: 'blog.posts.compressionMyths.title',
    descKey: 'blog.posts.compressionMyths.desc',
    contentKey: 'blog.posts.compressionMyths.content',
    date: '2026-07-23',
    readTime: 8,
    tags: ['compression', 'myths', 'quality', 'facts'],
    category: 'Knowledge',
  },
];
